#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check if the checkout was a branch checkout
if [ "$3" = "1" ]; then
    node tools/write-branch-name.js
else
    echo "File checkout detected, not running script."
fi
